"""test_migrate

Revision ID: 8790cb324bb1
Revises: 31ed38d48056
Create Date: 2021-02-04 17:25:36.931617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8790cb324bb1'
down_revision = '31ed38d48056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'posts', 'createpages', ['page_id'], ['id'])
    # ### end Alembic commands ###
